In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import folium

In [2]:
df = pd.read_csv('kc_house_data_clean.csv')
df.head()

Unnamed: 0            id        date     price  bedrooms  bathrooms  \
0           0  7.129301e+09  10/13/2014  221900.0       3.0       1.00   
1           1  6.414100e+09   12/9/2014  538000.0       3.0       2.25   
2           2  5.631500e+09   2/25/2015  180000.0       2.0       1.00   
3           3  2.487201e+09   12/9/2014  604000.0       4.0       3.00   
4           4  1.954401e+09   2/18/2015  510000.0       3.0       2.00   

   sqft_living  sqft_lot  floors  waterfront  ...      lat     long  \
0       1180.0    5650.0     1.0         0.0  ...  47.5112 -122.257   
1       2570.0    7242.0     2.0         0.0  ...  47.7210 -122.319   
2        770.0   10000.0     1.0         0.0  ...  47.7379 -122.233   
3       1960.0    5000.0     1.0         0.0  ...  47.5208 -122.393   
4       1680.0    8080.0     1.0         0.0  ...  47.6168 -122.045   

   sqft_living15  sqft_lot15    year  month   day  month_year   price_bands  \
0         1340.0      5650.0  2014.0   10.0  13.0     13-2014  200K to 300K   
1         1690.0      7639.0  2014.0   12.0   9.0      9-2014  500K to 600K   
2         2720.0      8062.0  2015.0    2.0  25.0     25-2015  100K to 200K   
3         1360.0      5000.0  2014.0   12.0   9.0      9-2014  600K to 700K   
4         1800.0      7503.0  2015.0    2.0  18.0     18-2015  500K to 600K   

                         location  
0             (47.5112, -122.257)  
1  (47.721000000000004, -122.319)  
2  (47.7379, -122.23299999999999)  
3  (47.5208, -122.39299999999999)  
4             (47.6168, -122.045)  

[5 rows x 28 columns]

In [3]:
df.columns

Index(['Unnamed: 0', 'id', 'date', 'price', 'bedrooms', 'bathrooms',
       'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition',
       'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated',
       'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15', 'year',
       'month', 'day', 'month_year', 'price_bands', 'location'],
      dtype='object')

Make a list of locations.

In [4]:
locations = list(df['location'])
locations[:5]

['(47.5112, -122.257)',
 '(47.721000000000004, -122.319)',
 '(47.7379, -122.23299999999999)',
 '(47.5208, -122.39299999999999)',
 '(47.6168, -122.045)']

In [5]:
list_long = np.array(df['long'])
list_long[:5]

array([-122.257, -122.319, -122.233, -122.393, -122.045])

In [6]:
list_lat = np.array(df['lat'])
list_lat[:5]

array([47.5112, 47.721 , 47.7379, 47.5208, 47.6168])

In [7]:
list_grade = np.array(df['grade'])
list_grade[:5]

array([7., 7., 6., 7., 8.])

## Basic Map

Just using the the first location as a starting point

In [8]:
map_basic = folium.Map(location=[47.5112, -122.257], zoom_start=13)

In [9]:
map_basic

## Check if markers work:

In [10]:
marker_test = folium.CircleMarker(location = [47.5112, -122.257], radius = 1)
marker_test.add_to(map_basic)

In [11]:
map_basic

In [12]:
marker_test = folium.CircleMarker(location = [47.7210, -122.319], radius = 1)
marker_test.add_to(map_basic)

map_basic

Make the lat & long into markers.

In [13]:
def to_marker(lat, long):
    return folium.CircleMarker(location=[lat, long], radius = 1)

In [14]:
markers = map(to_marker,[list_lat, list_long])

Add the markers to the map

In [15]:
def markers_to_map(markers, map_obj):
    for marker in markers:
        marker.add_to(map_obj)
    return map_obj

In [16]:
map_housing = map(markers_to_map, [markers, map_basic])

In [17]:
map_housing